scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/deploy.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/deployprod.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/canister_lds.json /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/Cargo.lock /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/Cargo.toml /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/claim.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/dev-univoice-dapp.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/dfx.json.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/dfxbackup.json.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/init-env.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/mintokendev.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/mintoken.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/nft-mint-ic.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/nft-mint.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/package.json /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/README.md /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/setup_dapp.sh /Users/senyang/AGC-DFX/
scp root@8.141.81.75:/root/univoice/icp/AGC-DFX/test_mugc_agc.sh /Users/senyang/AGC-DFX/
